name: Run Hurl Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HURL_VERSION: 4.3.0

jobs:
  hurl-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Hurl
      run: |
        curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/${{ env.HURL_VERSION }}/hurl_${{ env.HURL_VERSION }}_amd64.deb
        sudo apt update && sudo apt install ./hurl_${{ env.HURL_VERSION }}_amd64.deb

    - name: Run Hurl tests
      run: |
        mkdir -p ./results
        hurl --very-verbose --continue-on-error --test --report-html report/ --variables-file uat.env text_translate_normal.hurl

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: hurl-test-results
        path: ./results
