name: Run Hurl Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hurl-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Hurl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        echo "deb [trusted=yes] https://apt.fury.io/hurl/ /" | sudo tee /etc/apt/sources.list.d/hurl.list
        sudo apt-get update
        sudo apt-get install -y hurl

    - name: Run Hurl tests
      run: |
        mkdir -p ./results
        hurl --report-html ./results/report.html text_translate_normal.hurl

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: hurl-test-results
        path: ./results
