name: Run Hurl Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'environment'
        required: true
        default: 'uat'
        type: choice
        options:
          - qa
          - uat
          - production
      project:
        description: 'project'
        required: true
        default: 'live_translator'
        type: choice
        options:
          - aigc
          - live_translator

env:
  HURL_VERSION: 4.3.0

jobs:
  hurl-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Hurl
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/${{ env.HURL_VERSION }}/hurl_${{ env.HURL_VERSION }}_amd64.deb
          sudo apt update && sudo apt install ./hurl_${{ env.HURL_VERSION }}_amd64.deb

      - name: Run Hurl tests
        id: run_test  # 添加步骤 ID
        run: |
          make -B ${{ inputs.project }} env=${{ inputs.env }} > result.log 2> error.log
          echo "stderr<<EOF" >> $GITHUB_ENV  # 使用 GITHUB_ENV 设置环境变量
          cat error.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload Hurl Report
        uses: actions/upload-artifact@v3
        with:
          name: hurl-report
          path: live_translator/report/

      - name: Notify on Failure
        if: failure()
        uses: leafney/dingtalk-action@v1
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
        with:
          msgtype: actionCard
          title: 'TestSuites Failure: project=${{ inputs.project }} env=${{ inputs.env }}'
          text: |
            <h3>TestSuites Failure by @${{ github.actor }}</h3>
            <ul>
              <li><strong>项目</strong>: ${{ inputs.project }}</li>
              <li><strong>环境</strong>: ${{ inputs.env }}</li>
            </ul>
            <p><strong>错误日志</strong>:</p>
            <pre>${{ env.stderr }}</pre>  # 使用环境变量引用 stderr
          single_title: '查看详情'
          single_url: 'dingtalk://dingtalkclient/page/link?url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

      - name: Notify on Success
        if: success()
        uses: leafney/dingtalk-action@v1
        env:
          DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
        with:
          msgtype: actionCard
          title: 'TestSuites Success: project=${{ inputs.project }} env=${{ inputs.env }}'
          text: |
            <h3>TestSuites Success by @${{ github.actor }}</h3>
            <ul>
              <li><strong>项目</strong>: ${{ inputs.project }}</li>
              <li><strong>环境</strong>: ${{ inputs.env }}</li>
            </ul>
          single_title: '查看详情'
          single_url: 'dingtalk://dingtalkclient/page/link?url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
